### ISSUE TITLE
Is there an issue with parsing of robots.txt?

### ISSUE THREAD

**Issue by satyanath** [wikimedia/html-metadata#62]
I think there is some issue in parsing the robots.txt in html-metadata. I get the metadata as { general: { robots: 'noindex,nofollow' } } for the url https://www.sciencedaily.com/news/matter_energy/graphene/. But the robots.txt is as follows 

Sitemap: https://www.sciencedaily.com/sitemap-index.xml
User-agent: Yahoo Pipes 1.0
Disallow: /
User-agent: Yahoo Pipes 2.0
Disallow: /
User-agent: *
Disallow: /templates/
Disallow: /includes/
Disallow: /1002721/
Disallow: /v1/sciencedaily/

The robots.txt clearly allows scrapping but still html-metadata does not scrape. 

Or I am missing something here.

**Comment by satyanath** [comment]
Is there any possibility of this getting fixed in the near future?

**Comment by mvolz** [comment]
Hi, I am a little confused about what the problem is. 

html-metadata only gets metadata that is in html, so there won't be any information about robots.txt in any result you get from it. 

If there is robot information in the metadata in the html it can get that, i.e. <meta name ="robots" content="noindex,follow"> that is present in the html. However, when I look at the html of the page you have listed it does not contain such a metadata tag.

When I try to scrape the above url, I get:

{ general: 
   { canonical: 'https://www.sciencedaily.com/news/matter_energy/graphene/',
     description: 'Graphene. Read the latest research news on graphene, including special properties of the substance, potential uses as the \'new silicon\' and more.',
     title: 'Graphene News -- ScienceDaily',
     lang: 'en' },
  openGraph: 
   { title: 'Graphene News',
     type: 'article',
     url: 'https://www.sciencedaily.com/news/matter_energy/graphene/',
     description: 'Graphene. Read the latest research news on graphene, including special properties of the substance, potential uses as the \'new silicon\' and more.',
     site_name: 'ScienceDaily' } }

**Comment by satyanath** [comment]
I was not getting any metadata in the version I have. May be I need to update the version. Will try and check it again.

**Comment by satyanath** [comment]
Looks like something changed in the web page itself. As mentioned in the issue post I was getting the meta data as 

{ general: { robots: 'noindex,nofollow' } } 

now that is not the case. So closing this issue. Thanks for your response.
